class Routes {
  static Future<String> get initialRoute async {
    return SPLASH;
  }

  static const CALENDAR = '/calendar';
  static const DELETE_ACCOUNT_CONFIRMATION = '/delete-account-confirmation';
  static const DETAIL_INFO = '/detail-info';
  static const EDIT_PASSWORD = '/edit-password';
  static const FANCLUB = '/fanclub';
  static const FAN_CLUB_CONFIRMATION = '/fan-club-confirmation';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const FORGOT_PASSWORD_HOME = '/forgot-password-home';
  static const GALLERY = '/gallery';
  static const GALLERY_SCREEN_DETAIL = '/gallery-screen-detail';
  static const GAME_INFO = '/game-info';
  static const GAME_GUIDE = '/game-guide';
  static const GAME_GUIDE_DETAIL = '/game-guide-detail';
  static const TRAINING_GAME = '/training-game';
  static const TRAINING_GAME_LAUNCH = '/training-game/launch';
  static const TRAINING_GAME_NEW = '/training-game/new';
  static const HOME = '/home';
  static const INFO = '/info';
  static const LIST_TOPICS = '/list-topics';
  static const LOGIN = '/login';
  static const MAIN = '/main';
  static const MATCH_DETAIL = '/match-detail';
  static const MEMBER = '/member';
  static const MYPAGE = '/mypage';
  static const NOTIFICATION_DETAIL = '/notification-detail';
  static const NOTIFICATION_LIST = '/notification-list';
  static const PLAYER_DETAIL = '/player-detail';
  static const PRIVACY_POLICY_SCREEN = '/privacy-policy-screen';
  static const REGISTER_EMAIL = '/register-email';
  static const REGISTER_EMAIL_FROM_HOME = '/register-email-from-home';
  static const REGISTER_MEMBER_FANCLUB = '/register-member-fanclub';
  static const REGISTER_OTP = '/register-otp';
  static const RESET_PASSWORD = '/forgot-password';
  static const SPLASH = '/splash';
  static const STADIUM = '/stadium';
  static const TEAM = '/team';
  static const WALLPAPER = '/wallpaper';
  static const WALLPAPER_SET_PLAYER = '/wallpaper-set-player';
  static const WARNING_DIALOG = '/warning-dialog';
  static const WEBVIEW = '/webview';
  static const YEAR_FILTER_CONTROLLER = '/year-filter-controller';
  static const LOCAL_FULL_SCREEN = '/local-full-screen';
  static const POINT_TOP = '/points';
  static const POINT_EXPIRING = '/points/expiring';
  static const POINT_QR = '/points/qr';
  static const POINT_QR_PROCESSING = '/points/qr/processing';
  static const POINT_QR_RESULT = '/points/qr/result';
  static const POINT_HISTORY = '/points/history';
  static const POINT_HISTORY_DETAIL = '/points/history/detail';
  static const POINT_RANKING = '/points/ranking';
  static const POINT_REWARDS = '/points/rewards';
  static const POINT_REWARD_DETAIL = '/points/rewards/detail';
  static const POINT_EXCHANGE_CONFIRM = '/points/exchange/confirm';
  static const POINT_EXCHANGE_COMPLETE = '/points/exchange/complete';
  static const POINT_EXCHANGE_RECEIPT = '/points/exchange/receipt';
}
